# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-12 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['published_date']},
        ),
    ]
